// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    FMCard: typeof import('./components/FMCard.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    ForYouSection: typeof import('./components/ForYouSection.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconButton: typeof import('./components/IconButton.vue')['default']
    MusicCard: typeof import('./components/MusicCard.vue')['default']
    MusicSection: typeof import('./components/MusicSection.vue')['default']
    MusicSectionRow: typeof import('./components/MusicSectionRow.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Player: typeof import('./components/Player.vue')['default']
    PlaylistItem: typeof import('./components/PlaylistItem.vue')['default']
    RecommendCard: typeof import('./components/RecommendCard.vue')['default']
  }
}

export { }
