// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArtistInfo: typeof import('./components/ArtistInfo.vue')['default']
    FMCard: typeof import('./components/FMCard.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    ForYouSection: typeof import('./components/ForYouSection.vue')['default']
    IconButton: typeof import('./components/IconButton.vue')['default']
    MusicCard: typeof import('./components/MusicCard.vue')['default']
    MusicSection: typeof import('./components/MusicSection.vue')['default']
    MusicSectionRow: typeof import('./components/MusicSectionRow.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Player: typeof import('./components/Player.vue')['default']
    RecommendCard: typeof import('./components/RecommendCard.vue')['default']
    SearchTrackCard: typeof import('./components/SearchTrackCard.vue')['default']
    TrackslistInfo: typeof import('./components/TrackslistInfo.vue')['default']
    TrackslistItem: typeof import('./components/TrackslistItem.vue')['default']
  }
}

export { }
